In [3]:
import numpy as np
import pandas as pd

In [30]:
A = np.arange(1, 21).reshape(4,5)
B = np.arange(11, 31).reshape(4,5)

In [31]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
A.shape

(4, 5)

In [33]:
B

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
B.shape

(4, 5)

In [35]:
vert = np.vstack((A,B))

In [36]:
vert

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
vert.shape

(8, 5)

In [38]:
horz = np.hstack((A,B))

In [39]:
horz

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15, 21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20, 26, 27, 28, 29, 30]])

In [40]:
horz.shape

(4, 10)

In [41]:
# Common elements between A and B
intersection = np.intersect1d(A,B)
intersection

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
# Extracting elements from A in range from 2 to 9

subset = A[(A >= 2) & (A <= 9)]
subset

array([2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])


In [51]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [53]:
filtered_iris = iris_2d[(iris_2d[:,0]<5.0) & (iris_2d[:,2]>1.5)]
filtered_iris

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [54]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [55]:
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [63]:
df[["Manufacturer", "Model", "Type"]].iloc[::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [72]:
df = df.fillna(df["Max.Price"].mean())

In [74]:
df = df.fillna(df["Min.Price"].mean())

In [75]:
# Question 7
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [76]:
df

0   1   2   3
0   38  16  26  13
1   36  36  12  12
2   11  14  32  37
3   10  21  35  15
4   22  25  12  10
5   22  29  31  36
6   20  37  11  21
7   16  22  26  22
8   18  19  15  39
9   11  20  25  10
10  21  14  12  23
11  26  31  31  30
12  38  13  22  21
13  13  17  39  14
14  23  26  22  26

In [81]:
df.sum(axis =1)

0      93
1      96
2      94
3      81
4      69
5     118
6      89
7      86
8      91
9      66
10     70
11    118
12     94
13     83
14     97
dtype: int64

In [82]:
df_subset = df[df.sum(axis =1)>100]

In [83]:
df_subset

0   1   2   3
5   22  29  31  36
11  26  31  31  30